apiVersion: apps/v1
kind: Deployment
metadata:
  name: betterwellness-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: betterwellness-user
  template:
    metadata:
      labels:
        app: betterwellness-user
    spec:
      containers:
        - name: user-service
          image: cdkaluarachchi/user-service:latest 
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: JWT_SECRET
              value: "asdfasdwaewaew2"
            - name: MONGO_URI
              value: "mongodb+srv://cdkaluarachchi:sjhs4k@betterwellness.bdn3m38.mongodb.net/?retryWrites=true&w=majority&appName=betterwellness"
          
          readinessProbe:
            httpGet:
              path: /  
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: betterwellness-user-service
spec:
  selector:
    app: betterwellness-user
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP